version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app   # mount local code
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app   # mount local code
      - /app/node_modules # prevent overwriting node_modules
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend