name: Build Docker images (PR)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build Docker images'
        required: true
        default: 'latest'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build ./backend -t ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.tag || latest }}

      - name: Build frontend image
        run: |
          docker build ./frontend -t ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.tag || latest }}
